spring:
  application:
    name: LMS

  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: "your-super-secret-key-at-least-32-characters-long!"
    access-token-expiry-ms: 900000      # 15 min
    refresh-token-expiry-ms: 604800000  # 7 days